name: Cache Example

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/my-deps
          key: cache-8dc0be4

      - name: prime-cache-8dc0be4
        run: echo "Cache result: ${{ steps.cache-step.outputs.cache-hit }}"
